# Server
server.port=8085

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/gearup_payment
spring.datasource.username=postgres
spring.datasource.password=gearup123
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT
jwt.secret=404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
jwt.expiration=86400000

# Paystack
paystack.secret.key=sk_test_866c1f697d826c2f8ed3c987f464e29f847ad173
paystack.public.key=pk_test_672511ee747d3d4fe3b76b725903f377eaada95f
